version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel-net
        depends_on:
            - kafka

    web:
        image: nginx:alpine
        container_name: laravel-web
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-net
        depends_on:
            - app

    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - laravel-net

    redis:
        image: redis:7.2
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - laravel-net
    kafka:
        image: confluentinc/cp-kafka:7.6.0
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        networks:
            - laravel-net
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8081:8080"
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
            - kafka
        networks:
            - laravel-net

networks:
    laravel-net:
